searchfilters: FilterItem now 'implements' Serializable to fix Parcelable encountered IOException
The following Exception crashes NewPipe. Adding Serializable to FilterItem solves it:

java.lang.RuntimeException: Parcelable encountered IOException writing serializable object
(name = org.schabi.newpipe.extractor.linkhandler.ListLinkHandler)
...
Caused by: java.io.NotSerializableException: org.schabi.newpipe.extractor.search.filter.FilterItem